feat: Replace Fees Doctype with Sales Invoice
frappe/education pull request #181
Opened 2024-01-08 11:56 UTC by RitvikSardana

`no-docs`

2024-01-25 05:31 UTC, pateljannat requested changes

2024-01-25 05:31 UTC, pateljannat commented on education/education/doctype/fee_structure/fee_structure.js
> +						let fee_plan = dialog.get_value('fee_plan');
Put this in a separate function.

2024-01-25 05:31 UTC, pateljannat commented on education/education/doctype/program_enrollment/program_enrollment_dashboard.py
> +		"transactions": [{"label": _("Fees"), "items": ["Fees"]}],
Remove this

2024-01-25 05:31 UTC, pateljannat commented on education/education/doctype/student/student.json
> +   "fieldname": "default_price_list",
Verify this

2024-01-25 05:31 UTC, pateljannat commented on education/education/doctype/student/student_dashboard.py
> +			{"label": _("Fee"), "items": ["Sales Invoice", "Bank Account"]},
make this a link

2024-01-25 18:41 UTC, merged

2024-01-26 18:52 UTC, kodeli-lab commented
Please with the the above implementation how do you track outstanding amount or arrears for the previous semester. Is there a way to automatically include outstanding fees or arrears to the current semester fees. Example, If a student has an outstanding balance for the previous semeters, in the creation of fee schedules for the next semeter, the outstanding fee is automatically added.

2024-01-26 18:56 UTC, RitvikSardana commented
both are separate invoices for a student, if the student has not paid the fees, the invoice will show the status as overdue.